---

- hosts: all
  become: true
  tasks:

  - name: install apache and php for Ubuntu server
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for centos server
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Centos"

  
